version: '3.3'
services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - '9000:80'
  api:
    container_name: api
    build: ./backend/api
    ports:
      - '3000:3000'